spawn:
  ==: area
  world: "world"
  location: [12.5, 56, 2.5, 90, 0]

ffa:
  ==: mode
  world: "world"
  void_level: 30
  location: [169.5, 88, -387.5, 0, 0]
  region:
    ==: region
    a: [159, 85, -372]
    b: [180, 132, -393]

knockback:
  ==: mode
  world: "world"
  void_level: 54
  location: [ 20.5, 114, -580.5, 0, 0 ]
  region:
    ==: region
    a: [ 24, 110, -533 ]
    b: [ 16, 120, -587 ]

spleef:
  ==: spleef_mode
  world: "world"
  void_level: 20
  location: [ -327.5, 64, -118.5, -90, 0 ]
  region:
    ==: region
    a: [ -322, 63, -123 ]
    b: [ -331, 69, -115 ]
  floors:
    ==: classic_floors
    starting_y: 60
    layer_count: 6
    air_gap: 3
    x1: -322
    x2: -298
    z1: -107
    z2: -131

tntrun:
  ==: spleef_mode
  world: "world"
  void_level: 10
  location: [ -416.5, 49, -19.5, 90, 0 ]
  region:
    ==: region
    a: [ -423, 48, -16 ]
    b: [ -414, 53, -24 ]
  floors:
    ==: tnt_floors
    starting_y: 46
    layers:
      - "minecraft:red_concrete_powder"
      - "minecraft:orange_concrete_powder"
      - "minecraft:yellow_concrete_powder"
      - "minecraft:lime_concrete_powder"
      - "minecraft:light_blue_concrete_powder"
    air_gap: 3
    x1: -423
    x2: -447
    z1: -32
    z2: -8

leaderboard: